### ISSUE TITLE
Error while oppening the source in vs

### ISSUE THREAD

**Issue by Faarhad** [ValerCheck/CloudSim.Net#3]
Hi there, I am so glad when I see your valuable work to refactor Cloudsim in C#.
I just extract the source files and by opening the SLN file a bunch of errors appeared, can you explain what is wrong with this?
(please check the attached file)
Thank you in advance
![Screenshot 2021-05-12 125103](https://user-images.githubusercontent.com/11638612/117942856-c2980480-b320-11eb-9b5e-56369d0a6dcb.png)

**Comment by ValerCheck** [comment]
Hi, @Faarhad. Unfortunately, I have almost abandoned work on this project due to massive changes in original CloudSim.
However, I have started new project based on R 'simmer' framework regarding IT infrastructure simulations.

**Comment by ValerCheck** [comment]
However, if you are interested exactly in C# version, I can try to port 'simmer'-based solution to C#.

**Comment by Faarhad** [comment]
Hi @ValerCheck , thank you for your quick reply. I need to use CloudSim based simulator like workflowsim to do some research. So, it is probably not necessary to change "simmer" in C#. Although I'll check this project out.
